# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQaITi0YMwP5TavD8n5t_OpAgALKw8Yu
"""

import random

# List of words to choose from
word_list = ['python', 'hangman', 'programming', 'challenge', 'ateeq']

def select_random_word(word_list):
    """Select a random word from the word list."""
    return random.choice(word_list)

def display_current_progress(word, guessed_letters):
    """Display the current progress of the word being guessed."""
    display_word = ''.join([letter if letter in guessed_letters else '_' for letter in word])
    print('Current word: ' + ' '.join(display_word))

def play_hangman():
    """Play a game of Hangman."""
    word = select_random_word(word_list)
    guessed_letters = set()
    incorrect_guesses = 0
    max_incorrect_guesses = 6

    print("Welcome to Hangman!")

    while incorrect_guesses < max_incorrect_guesses:
        display_current_progress(word, guessed_letters)
        guess = input("Guess a letter: ").lower()

        if len(guess) != 1 or not guess.isalpha():
            print("Please enter a single letter.")
            continue

        if guess in guessed_letters:
            print("You have already guessed that letter.")
            continue

        guessed_letters.add(guess)

        if guess in word:
            print(f"Good guess! '{guess}' is in the word.")
            if all(letter in guessed_letters for letter in word):
                print(f"Congratulations! You have guessed the word '{word}' correctly.")
                break
        else:
            incorrect_guesses += 1
            print(f"Sorry, '{guess}' is not in the word. You have {max_incorrect_guesses - incorrect_guesses} incorrect guesses left.")

    if incorrect_guesses == max_incorrect_guesses:
        print(f"Game over! The word was '{word}'.")

if __name__ == "__main__":
    play_hangman()